import { randomUUID } from "node:crypto"
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises"
import { dirname, relative, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"

const packageRoot = fileURLToPath(new URL("../", import.meta.url))

// Frozen legacy API compatibility lists preserve the existing enumeration and
// schema-option orders. New model folders need no entry here and sort by path.
const registrationOrder = [
  "hexbolt",
  "helicalgear",
  "nema",
  "sheetmetal",
  "flexscreen",
  "hexsocketbolt",
  "spurgear",
  "wormgear",
]
const schemaOrder = [
  "hexbolt",
  "nema",
  "sheetmetal",
  "flexscreen",
  "hexsocketbolt",
  "helicalgear",
  "spurgear",
  "wormgear",
]

export interface GenerateModelRegistryOptions {
  modelsDir?: string
  outputFile?: string
  registryModuleSpecifier?: string
}

export interface GeneratedModelRegistry {
  source: string
  changed: boolean
  modelDirectories: string[]
}

function compareWithOrder(order: string[], left: string, right: string) {
  const leftIndex = order.indexOf(left)
  const rightIndex = order.indexOf(right)
  if (leftIndex !== -1 || rightIndex !== -1) {
    if (leftIndex === -1) return 1
    if (rightIndex === -1) return -1
    return leftIndex - rightIndex
  }
  return left < right ? -1 : left > right ? 1 : 0
}

function moduleSpecifier(outputFile: string, target: string) {
  const path = relative(dirname(outputFile), target).split(sep).join("/")
  return path.startsWith(".") ? path : `./${path}`
}

export async function generateModelRegistry(
  options: GenerateModelRegistryOptions = {},
): Promise<GeneratedModelRegistry> {
  const modelsDir = resolve(options.modelsDir ?? `${packageRoot}/src/models`)
  const outputFile = resolve(
    options.outputFile ?? `${packageRoot}/src/generated/models.ts`,
  )
  const registryModule = options.registryModuleSpecifier ?? "../model-registry"
  const folders: string[] = []
  for await (const path of new Bun.Glob("*/register.ts").scan({
    cwd: modelsDir,
    onlyFiles: true,
    dot: true,
  })) {
    folders.push(dirname(path))
  }
  if (folders.length === 0) {
    throw new Error(`No model registration adapters found in ${modelsDir}`)
  }
  folders.sort((left, right) =>
    compareWithOrder(registrationOrder, left, right),
  )
  const schemaFolders = [...folders].sort((left, right) =>
    compareWithOrder(schemaOrder, left, right),
  )
  const imports = folders.flatMap((folder, index) => {
    const path = JSON.stringify(
      moduleSpecifier(outputFile, resolve(modelsDir, folder, "register")),
    )
    return [
      `import { model as model${index} } from ${path}`,
      `import { register as register${index} } from ${path}`,
    ]
  })
  const schemaNames = schemaFolders.map(
    (folder) => `model${folders.indexOf(folder)}.schema`,
  )
  const schema =
    schemaNames.length === 1
      ? schemaNames[0]
      : `z.union([\n${schemaNames.map((name) => `  ${name},`).join("\n")}\n])`
  const source = [
    "// Generated by scripts/generate-model-registry.ts. Do not edit.",
    'import { z } from "zod"',
    `import type { ModelRegistry } from ${JSON.stringify(registryModule)}`,
    ...imports,
    "",
    `export const builtinModels = [\n${folders.map((_, index) => `  model${index},`).join("\n")}\n] as const`,
    "",
    `export const modelDefinitionSchema = ${schema}`,
    "export type ModelDefinition = z.infer<typeof modelDefinitionSchema>",
    "",
    "export function registerAllModels(registry: ModelRegistry): void {",
    ...folders.map((_, index) => `  register${index}(registry)`),
    "}",
    "",
    ...folders.map(
      (folder) =>
        `export * from ${JSON.stringify(moduleSpecifier(outputFile, resolve(modelsDir, folder)))}`,
    ),
    "",
  ].join("\n")

  let existing: string | undefined
  try {
    existing = await readFile(outputFile, "utf8")
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
  }
  if (existing === source) {
    return { source, changed: false, modelDirectories: folders }
  }

  await mkdir(dirname(outputFile), { recursive: true })
  const temporaryFile = `${outputFile}.${process.pid}.${randomUUID()}.tmp`
  try {
    await writeFile(temporaryFile, source, { flag: "wx" })
    await rename(temporaryFile, outputFile)
  } finally {
    await unlink(temporaryFile).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== "ENOENT") throw error
    })
  }
  return { source, changed: true, modelDirectories: folders }
}

if (import.meta.main) {
  await generateModelRegistry()
}
